
version: '3'
services:
  postgres:
    image: ${DOCKER_REGISTRY}/postgres:9.6.11
    container_name: postgresqljfrog
    environment:
     - POSTGRES_DB=${DB_NAME}
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=${DB_PASSWD}
    ports:
      - 5432:5432
    volumes:
     - ${ROOT_DATA_DIR}/var/data/postgres/data:/var/lib/postgresql/data
     - /etc/localtime:/etc/localtime:ro
    networks:
     - jfrog
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  artifactory:
    image: ${DOCKER_REGISTRY}/jfrog/artifactory-pro:${ARTIFACTORY_VERSION}
    container_name: artifactory
    volumes:
     - ${ROOT_DATA_DIR}/var:/var/opt/jfrog/artifactory
     - /etc/localtime:/etc/localtime:ro
    networks:
     - jfrog
    restart: always
    depends_on:
     - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/artifactory/api/system/ping"]
      interval: 30s
      timeout: 5s
      retries: 5
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    environment:
     - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
    ports:
      #- 3380:80 # nginx port
      - ${HOST_HTTPS_PORT}:443 # nginx port
      - ${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}:${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT} # for router communication
      - 8081:8081 # for artifactory communication
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
  nginx:
    image: ${DOCKER_REGISTRY}/jfrog/nginx-artifactory-pro:${ARTIFACTORY_VERSION}
    container_name: nginxjfrog
    depends_on:
     - artifactory
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://localhost:443/artifactory/api/system/ping"]
      interval: 30s
      timeout: 5s
      retries: 5
    network_mode: service:artifactory
    volumes:
     - ${ROOT_DATA_DIR}/var/data/nginx:/var/opt/jfrog/nginx
     - /etc/localtime:/etc/localtime:ro
     - ${RSC_PATH}/certificates/server.crt:/var/opt/jfrog/nginx/ssl/example.crt:ro
     - ${RSC_PATH}/certificates/server.key:/var/opt/jfrog/nginx/ssl/example.key:ro
    environment:
     - ART_BASE_URL=http://artifactory:${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
     - SSL=true
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

networks:
  jfrog: {}

