apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-storage-pv
  labels:
    type: vault-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: <NFS-server-share-path>
    server: <NFS-server-IP-address>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""