kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vault-storage
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi             